# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercut < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/homebrew-papercut"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.1.0/homebrew-papercut_Darwin_arm64.tar.gz"
      sha256 "30748f83bc5bb2686cee48d10f720535118acc28ae4049222d2c46ae6b40598a"

      def install
        bin.install "papercut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.1.0/homebrew-papercut_Darwin_x86_64.tar.gz"
      sha256 "87de49a06521e9b818224519c9736d13a1a463045b55636cd659763d13874c92"

      def install
        bin.install "papercut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.1.0/homebrew-papercut_Linux_arm64.tar.gz"
      sha256 "d015e71a33734ee8be8e7f9317a04629ed53876a2d2fef8eafa508a6cd3bf570"

      def install
        bin.install "papercut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.1.0/homebrew-papercut_Linux_x86_64.tar.gz"
      sha256 "2beb8dc70da7464145ce234d6117e14f30eeccc7a4414607dbdfbbbdc229c457"

      def install
        bin.install "papercut"
      end
    end
  end
end
