# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercut < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/homebrew-papercut"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.0.3/homebrew-papercut_Darwin_arm64.tar.gz"
      sha256 "d86db350d615a5ef437fe93b212fbbc8ee0f434ce1127049be657c4bf7baf9d1"

      def install
        bin.install "papercut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.0.3/homebrew-papercut_Darwin_x86_64.tar.gz"
      sha256 "2829a54ab610d2f575dbf58cb2ee04e301051259b10f15037e87d44514c8f64f"

      def install
        bin.install "papercut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.0.3/homebrew-papercut_Linux_arm64.tar.gz"
      sha256 "1e5dd612141bccae805ab2768d0b53ce902b3a4fc03fcd57e8c40842d793c0a5"

      def install
        bin.install "papercut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/homebrew-papercut/releases/download/v0.0.3/homebrew-papercut_Linux_x86_64.tar.gz"
      sha256 "55223a8c4f0d6e8261f6b0ca99641187089a79fdff3e1e84781ab62ef5e3cf6a"

      def install
        bin.install "papercut"
      end
    end
  end
end
